### ISSUE TITLE
uI3

### ISSUE THREAD

**Issue by marvinstuart** [bp2008/ui3#1]
Excellent Job, on the Ui3 

- Since many user don't have PTZ cameras would it be possible to have the ability to enable / disable PTZ view     
- Add a frame around each camera   
- When touching either live | alert | clips use another colour than blue as it clashes with the blue used on the system name
-

**Comment by bp2008** [comment]
Hello, and thank you for the feedback!

Regarding the PTZ controls, I am not sure if there is much genuine benefit to hiding them on systems that don't have PTZ.  Then, instead of disabled PTZ controls, you just have blank space.  This would potentially allow you to stay on the largest UI scale with a smaller browser window, but that is the only meaningful effect I think, and not necessarily a good effect either.

Early on, I considered a frame around each camera to match what you get in Blue Iris's local GUI, but I decided against it.  Mostly, I don't like how much more complex it would make the UI.  Once you have frames around each camera, there is an expectation to be able to select a camera by clicking it (and for selecting the camera to actually mean something).  Maximizing the camera then takes a double-click.  There is an expectation that you will be able to reorder or resize the camera frames, or hide a specific camera, etc, which would require the web UI to have its own complex camera layout engine.  Efficiency and image quality would go straight out the window, too, once the UI is cropping and resizing individual sections of the group video stream.  H.264 group playback in particular would become much more taxing on the CPU, to the point of unusability on a system that would have otherwise handled it fine. 
 There are also implications for how digital zoom is handled.  And likely other problems I never even thought of.

About the color bar on the selected tab, I didn't think it looked bad at all being the exact same color as the system name background.  If you can convince me another color is better, I'll be happy to change it though.
