### ISSUE TITLE
Wrong camera displayed or unable to click camera

### ISSUE THREAD

**Issue by mr-bobdobalina** [bp2008/ui3#102]
Ever since UI3-197 I have noticed only half of my cameras are displayed correctly. Some cameras I click on it and get a different camera displayed.  Other cameras clicking on it does nothing at all.  I reverted to UI3-196 and everything is fine. My Blue Iris version is 5.5.4.3. Unable to upgrade because my support license has expired.  If release 197 and beyond need a newer BI version please say so in the release documentation.

**Comment by bp2008** [comment]
You are correct.  197 has a breaking change which loads group layout metadata from HTTP headers that did not exist in older BI releases.  I will make a note of this in the release notes.

Generally I don't worry about backwards compatibility in UI3 since it is distributed with Blue Iris.  I do try to note when there's a breaking change but 197 had so many changes, it slipped my mind to mention this one would break backwards compatibility.
