### ISSUE TITLE
Timeline Error Displayed

### ISSUE THREAD

**Issue by kskcheche** [bp2008/ui3#108]
Blueiris UI3 Timeline 

This is shown in the timeline 
Server response did not indicate "success" result: {"result":"fail","session":"--SessionID#--","date":{"colors":[],"alerts":[],"clips":[]}}

UI3 version 212, Blue Iris version: 5.3.6.6Blue Iris

**Comment by bp2008** [comment]
The timeline isn't available in UI3 until Blue Iris 5.5.6.

**Comment by kskcheche** [comment]
I could see it before in UI3, I just updated from stock to current. Something must be wonky with my BI.

**Comment by bp2008** [comment]
Hmm.  I suggest you double-check your Blue Iris version.  Also note that UI3 does not maintain backwards compatibility with older Blue Iris releases, so it is only usually safe to update UI3 manually if you are running the bleeding edge latest release of Blue Iris.  Certainly a lot has changed since BI 5.3.6.6 (that was about 17 months ago!) so a lot of UI3 components would be broken if you were running version 212.
