### ISSUE TITLE
Disable or decrease automatic login countdown [Feature request]

### ISSUE THREAD

**Issue by ahaverty** [bp2008/ui3#137]
Would it be possible to disable this countdown? I seem to hit it most of the time, which slows me down by 3s, checking on who's walking up to my door.
Perhaps a non-default setting somewhere to disable it entirely would be nice if there's no technical reason for needing the countdown? (i.e I'd imagine you can still log out if you want to switch user etc)

**Comment by bp2008** [comment]
If you right click on the checkbox or log in button, you can disable the countdown.  I know it isn't terribly intuitive but I really didn't want to make the form any taller than it already is to help avoid scrolling on touchscreens.  Because I have long since made it so that logging out of UI3 using the button in the main menu temporarily disables auto login, I should probably just eliminate the countdown altogether.

**Comment by bp2008** [comment]
Yeah I intend to remove the delay and the context menu option in the near future.

**Comment by bp2008** [comment]
I am quite sure the setting for instant vs delayed login is not related to this issue where the login page is skipping automatic login when you don't want it to.  The instant/delayed setting is only read after the decision to automatically log in has been made, and the UN/PW form fields have been programmatically filled out.

I'll do a thorough code review.  Lets see...

The login.htm page is sometimes instructed to skip automatic login via a URL parameter `autologin=0`.  This parameter is automatically stripped from the URL upon loading the login page so you would not normally see it in the address bar longer than a split second.

This URL parameter `autologin=0` is only sent in two situations:

1. If you use the "Log Out" button in UI3's main menu.
2. If the `libs-ui3.js` or `ui3.js` files fail to load from the Blue Iris server and get an HTTP 403 response, then UI3 will show an alert message "Your web server session was lost, probably because of a problem with the session cookie. Redirecting to login page.".  It requires the user to click a button to dismiss it, then you're immediately navigated to the login page with the `autologin=0` parameter set.

Since both of those situations require deliberate user interaction to proceed, I think neither of those will be the cause of your login page not respecting the "log in automatically" function.

There is one further mechanism which the login page uses to skip automatic login, and it is more complicated.

When the UI3 page gets unloaded (`beforeunload` event in JavaScript), it saves the current date and time into localStorage.  The login.htm page looks at this saved date and time, and if that was within 5 seconds of the time the login page loaded, then automatic login will be skipped.  This happens because it is assumed that when the login page loads within 5 seconds of UI3 unloading, it means the user navigated intentionally from UI3 to the login page (e.g. by pressing the back button, entering a URL in an address bar, clicking a bookmark or link, etc.) and it would be inappropriate to suddenly leave the login page.

There are complexifying factors of course.

When UI3 detects that the session is lost (such as after it was in the background for over a minute on a mobile device), automatic session recovery is performed.  If session recovery fails for any reason, it will show some toast messages and 3 seconds later it reloads the page with the date and time saved as "0" so that the login page will specifically NOT skip automatic login.

Also when you change certain UI settings such as the choice of H.264 video player, UI3 will prompt with a toast to have you reload the page, and if you reload by clicking the toast message then the date and time is saved as "0" just on the offchance that you end up getting redirected to the login page, so that it WILL automatically log you back in.

Also when the ui3.htm page loads, and it queries Blue Iris to find out the details of the session, it is possible that Blue Iris will respond that the session is invalid (e.g. expired).  In this case you get the toast message "The current session is invalid or expired.  Reloading this page momentarily." and the page reloads after 3 seconds, again with the date and time saved as "0" so that automatic login will occur.  This could happen if, for example, the ui3.htm page loaded from cache so the session string embedded in the HTML was outdated.

Anyway, I do not see how you could be clicking a notification and be immediately sent to the login page with automatic login being skipped, without some kind of message telling you something went wrong showing for at least 3 seconds before going to the login page.

When you click the notification, do you get sent to UI3 at all, even briefly, before the login page loads?  Or does it seem to be going directly to the login page first thing?

Perhaps when you click the notification and it loads the PWA, the previous UI3 instance (which has presumably been in the background long enough for your session stored in a cookie to become invalid) UI3 runs its `beforeunload` event.  This makes the date and time get saved.  Then the login page loads, sees that UI3 was just running a moment ago, and skips the automatic login.

I hope that is it.  Either way I should probably figure out a way to have UI3 realize it was not actually active just before the `beforeunload` event was fired.  Perhaps I also pay attention to how long it has been since the page last became active and if it was, say, just activated within 2 seconds and now the page is unloading, then we don't save the date and time.  Hmm..  Or instead of saving the current date/time, I could save the date/time of the last time UI3 received a JSON response or a video or audio frame from the Blue Iris server.  There's a small chance that a backgrounded UI3 instance could have such a JSON response or video/audio frame queued awaiting processing when its script engine got paused, only for it to get processed suddenly just before the UI unloads, thereby causing the undesired behavior to occur...

**Comment by bp2008** [comment]
I'm not sure you'll be able to debug in the PWA version, particularly during the moment just after you've clicked a notification.  But if so, search for `settings.bi_lastunload` around line `3375` of `ui3.js`.  See if the `isReloadingUi3` flag is true 
or not when the `beforeunload` event handler executes.  I'm assuming it will be false.  I'm also assuming that this event handler is running just prior to the login.htm page loading.  On login.htm, you can put a breakpoint at line 210 where `skipAutoLogin` gets declared, and step through and look at where and how it gets changed.  Then forward on line 259 (`if (GetPersistedValue("bi_rememberMe") === "1")` is where the automatic login code happens.

**Comment by bp2008** [comment]
I've made changes related to this in UI3-236.  Please test and see if your notification clicks work.

## [Version 236](https://github.com/bp2008/ui3/releases/tag/236)
* If a UI3 instance is closed within 2 seconds of becoming an active tab, it will no longer attempt to suppress automatic login.  This is intended to fix an issue on mobile devices where UI3 was installed as a progressive web app, where clicking an alert notification that links to UI3 could yield the login page with automatic login not working.
* When a UI3 instance is being gracefully closed, a note will be written to the console indicating whether and why automatic login is or is not being suppressed.
* login.htm Version 28.
  * The 2-second automatic login delay has been removed.
    * The context menu for toggling the 2 second delay has also been removed.
  * When automatic login is temporarily disabled, the reason is now logged to the console.
