### ISSUE TITLE
Samsung TV Browser throws ReferenceError

### ISSUE THREAD

**Issue by ryanandres** [bp2008/ui3#14]
See attached image below for error message.

This is on a Samsung TV (Q9F) in its browser app. Everything works as expected until I hit the back button which opens the TV's menu. Looks like some kind of onUnfocus event doesn't know what to do on the TV's browser.

![image](https://user-images.githubusercontent.com/1004699/46054082-85908c80-c0fa-11e8-8905-ebce30034316.png)

**Comment by bp2008** [comment]
Unfortunately that looks like a script error caused by some script injected by the TV's browser, and UI3 catches and reports all script errors this way.

You can try extracting this `ui3-local-overrides.js` file to your `Blue Iris 4/www/ui3` directory and see if it prevents the error message.  It is a simple script that overrides the global error handler and suppresses it if the error message contains the text "vc_request_action".

[ui3-local-overrides.zip](https://github.com/bp2008/ui3/files/2417967/ui3-local-overrides.zip)

Let me know if this completely solves the issue for you.  If the misbehaving script executes before the local overrides file gets loaded, you would still get the error message at least once at each page load.  If that is the case, I would need to suppress this particular error message in the stock UI3 release.

**Comment by ryanandres** [comment]
This solves the issue. Now I'm wondering what they're injecting! Thank you
