### ISSUE TITLE
UI3 dont let my computer sleep.

### ISSUE THREAD

**Issue by nandobarreto** [bp2008/ui3#151]
Recently I updated my UI3 from version 173 to the most recent (275), after that my computer (the remote, not the server with blueiris) stopped to sleep.
running the command I get powercfg -requests it shows:
[DRIVER] Realtek High Definition Audio (HDAUDIO\FUNC_01&VEN_10EC&DEV_0897&SUBSYS_1458A194&REV_1004\5&22057c6f&0&0001)
An audio stream is currently in use.

but i have the audio off on the stream. 
I tested everything and it only happens with UI3.
There is any config I can change to solve that? With teh version 173 I didnt have this problem.

**Comment by bp2008** [comment]
heh heh.  Just goes to show one man's feature is another man's problem.

I could add a settings toggle to turn off screen keepalive function that was added in UI3-233, however it would usually be ineffective because the HTML5 video player which is in use by default has its own keepalive feature that can't be turned off.

**Comment by nandobarreto** [comment]
> heh heh. Just goes to show one man's feature is another man's problem.
> 
> I could add a settings toggle to turn off screen keepalive function that was added in UI3-233, however it would usually be ineffective because the HTML5 video player which is in use by default has its own keepalive feature that can't be turned off.

I figured out that this problably was a feature and not a issue, that's why I closed, in the end I'll close the tab when I leave my computer (so it can rest), when I return i just need to open the tab again.
