### ISSUE TITLE
Access on 1 domain

### ISSUE THREAD

**Issue by studentAlanMorgan** [bp2008/ui3#160]
Hello, I would like to know if it is possible to make the transition to the server happen only from 1 domain?
so that there is no direct access to the web server via IP.
for example, if you enter ip/ui3.htm in the browser, the server will return an error, but if you make the transition from mysite.com, then access is opened.
This is how my media server works.

**Comment by bp2008** [comment]
Blue Iris does not support that natively, but you can achieve it with reverse proxy software.

For example https://github.com/bp2008/WebProxy which I wrote myself.

**Comment by studentAlanMorgan** [comment]
@bp2008 
I apologize for the impudence, but you can read more about this somewhere. How can I set up exactly what I have in mind?

**Comment by bp2008** [comment]
Well here is a basic setup guide I wrote for doing proxying to Blue Iris:  https://ipcamtalk.com/threads/webproxy-gui-based-alternative-to-stunnel.72203/

During the setup, you are asked to fill in a `Host Binding` field, and that is where you put the domain name.

Like this:
![image](https://github.com/bp2008/ui3/assets/5639911/100089b0-20a8-4d1d-96cc-ad8fa0fb6fd5)

The WebProxy server will only send the traffic to the destination origin when the hostname entered in the browser matches one of the hostnames in the Host Binding.  So in this case the hostname would need to be `mysite.com`, and if you entered the IP address directly, then the WebProxy server would simply close the connection.

Of course this all depends on you understanding how port numbers work and how to configure your PC, firewall, router, and DNS records correctly to send the traffic to the WebProxy service instead of directly to Blue Iris.

**Comment by studentAlanMorgan** [comment]
@bp2008 Thank you. I appreciate your work.
