### ISSUE TITLE
Allow user to change thumbnail size in IOS browser.

### ISSUE THREAD

**Issue by tschwei** [bp2008/ui3#24]
I love your UI, clean look and the extensive customization options.
I would really love it if you could find any kind of workaround/fix to allow context menu in IOS browsers.  But if you can’t, could you at least let us change the alert/clip thumbnail size?
Thanks!
Tim

**Comment by bp2008** [comment]
Hi.  There is an option to change the context menu trigger to double-click near the bottom of UI Settings.  It is far from ideal but if I remember correctly that option might work on iOS.

**Comment by tschwei** [comment]
Yes, I should have mentioned that I tried all those settings in Safari and Chrome, and none of them work on my iPad.  Could you maybe add a preference checkbox in the settings to enable large/small thumbnails?

Thanks,
Tim

**Comment by bp2008** [comment]
Yeah, I will put it in the Extra section somewhere.

I will also try to get in a context menu mechanism that works on iOS.  Even if it means making single-click an option (gosh that would be painful).

**Comment by bp2008** [comment]
I got the context menu triggers working on iOS.  Internally the behavior of the "Right-Click" and "Long-Press" triggers will be identical on iOS so you can choose either of those for best results.

I ended up not adding the clip list thumbnail size option to UI Settings.

UI3 version 80 has the fix.  It should be delivered in the next BI5 update, or you can install manually.  If installing manually, be aware that since version 78, deleting multiple clips/alerts now requires Blue Iris 5.0.0.54 or newer.  Everything else should still work in BI 4.

**Comment by tschwei** [comment]
Thank you!
I’m looking forward to trying it out.
Thanks,
Tim
