### ISSUE TITLE
H.264 alert/Clips

### ISSUE THREAD

**Issue by marvinstuart** [bp2008/ui3#4]
I notice with the latest update of UI3 re H.264 module, when viewing realtime the stream quality starts off poorly then after a few seconds it get better when viewing from my desktop. However when on my phone this doesn't happen which is perfect . The only issue is when i am reviewing alerts on my desktop or phone which are typically 10 sec the quality is poor due to the H.264  

Its it possible then viewing alert or clips its set to view in jpeg mode     
(i hope i am making sense)  
Mavrin

**Comment by bp2008** [comment]
I just pushed a new update.

Anyway, check the Streaming Quality option.  There are 3 options for H.264 corresponding to the 3 encoding configurations in Blue Iris > Web Server tab.  If your quality starts bad and gets better, that means your bit rate isn't high enough.

Also UI3 can handle "superfast" and "veryfast" encoding profiles, and is not limited to the "ultrafast" profile like UI2 is.  "ultrafast" is worse quality.

UI3 does not switch automatically to jpeg mode for clips anymore.

**Comment by marvinstuart** [comment]
thanks for the quick update in code . I change it from superfast to very fast. additional i am getting errors with new update see screen shot below
https://photos.app.goo.gl/y95mOEXYPGJmmXrs1

**Comment by bp2008** [comment]
Your browser has cached an old version of the file.  As this UI is pre-release, I have not been adding version numbers to the script callouts so that can happen.

It may work to refresh/reload the page (via the button in the browser, **not** by clicking the bookmark or by typing the address again).  Otherwise you'll need to figure out how to clear the browser cache.

**Comment by marvinstuart** [comment]
Resolved i just cleared cache , cookies and history and all is  working now . Just little clean up suggestion in the quality drop down i see you have H.264 streaming 0 , H.264 streaming 2  ,H.264 streaming 3. for a end they may not know what is the difference. 

Actually if you think about it does the average end user like my wife or kids really care, all they want is to the get best results and even they cared how often do they need or want change it, Its like anything we do in life if you dont use it regularly we put it somewhere until we are ready to use it. So maybe in the system configuration area move this option.

**Comment by bp2008** [comment]
I know the names suck.  I would love to have "1080p", "720p", "480p", etc as options since those are what people are used to seeing on youtube, but Blue Iris doesn't give me that kind of control.  Client apps have no control over the encoding settings except to choose from one of the 3 encoder profiles that can be configured in Blue Iris on the Web Server tab.  They are literally called "Streaming 0", "Streaming 1", and "Streaming 2" in Blue Iris so that is what I called them in the web UI.

Sometimes you want H.264 streaming for the higher frame rate, but it sucks when you zoom in because currently the H.264 is locked to a max resolution of 1280x720.  So if you need to zoom in on a fine detail you need to switch to jpeg mode.  For this and other reasons I am definitely keeping the option easily accessible.

**Comment by marvinstuart** [comment]
thanks as always . i see you a have potential  feature list . AWESOME
