### ISSUE TITLE
Add option to sort by memo text

### ISSUE THREAD

**Issue by Lazersfly** [bp2008/ui3#47]
I am integrating blue iris with AITool and it can provide a memo text of detected objects, could you add a search field where I could search for all alerts containing the work "person", "truck", etc, in the memo text? If so would it be possible to search for multiple objects at a time, ex "person" and "truck" in the same alert? The memo text is semicolon separated, ex "Bicycle (93.91%); Person (99.94%)". Thanks!

**Comment by bp2008** [comment]
Hi.  Sorry for not replying to this earlier.  Unfortunately, I do not have time to add such a niche feature when it isn't trivially simple to do.  Part of the problem is that Blue Iris's alert list API doesn't support searching the memo, so it would all have to be done clientside which severely limits the size of the result set and therefore the potential usefulness of the feature.
