### ISSUE TITLE
Seek bar "zoom in"

### ISSUE THREAD

**Issue by s-pw** [bp2008/ui3#63]
Currently, it is impossible to use seek bar to find an event that didn't generate an alert in a long clip. 
The resolution for 24h clip is 1 minute per pixel which is too long to catch something like a passing car that was missed by motion detection.

It would be nice if you could "zoom in" seek bar when the mouse is over it. 

The next step after "zoom in" would be to allow "zooming out" beyond the clip to allow seamlessly seeking through multiple clips for systems that do 24x7 recording.

An example feature is available in Google Nest surveillance cameras:
![zoomIn](https://user-images.githubusercontent.com/36118444/107288735-c746d700-6a18-11eb-8b75-18f0ae8b4324.gif)

**Comment by bp2008** [comment]
Hi.

I like how that looks.  Something that has been on my long-term roadmap for years is having "Timeline" tab at the top which would work a lot like that.  Unfortunately, my priorities often do not align with those of the Blue Iris developer, hence this being on my roadmap for years.

Without additional support from Blue Iris, the best I could do is a half-assed timeline offering only single-camera-playback.  Also, it would have very poor support for systems that record on motion detection and combine events into few(er) clips, which I believe is the default configuration.  When recording is done this way, UI3 doesn't know which time ranges have video available.

The more people request this from Blue Iris support, the higher the priority will be for him.  Please send a request to him!

In the meantime suggest you use these to skip forward or back in a smaller interval:

![image](https://user-images.githubusercontent.com/5639911/107306014-48b25f80-6a41-11eb-8712-4245f41a3eb3.png)
![image](https://user-images.githubusercontent.com/5639911/107306023-4fd96d80-6a41-11eb-9fc5-10b566c993d5.png)

**Comment by aesterling** [comment]
I've heard the BI dev hint at improved timeline support for UI3 and potentially the mobile apps "later this year" during a few of the webinars. Have you heard anything about that or know if it would allow the capabilities needed to implement a functional timeline?

**Comment by bp2008** [comment]
That is good to hear. I haven't watched most of the webinars, so I have no idea what was mentioned.  It sounds like he's at least aware that I'm eager to implement proper timeline playback.

I sent the BI dev some notes yesterday about what I want/need for timeline support.  Whether this gets the ball rolling or if it doesn't start for months yet, I have no idea.

**Comment by aesterling** [comment]
Another vague mention of expanded "timeline playback options" for UI3 in today's BI webinar:

<img width="335" alt="Screen Shot" src="https://user-images.githubusercontent.com/18314707/107802007-6a079a00-6d26-11eb-9564-0430c056c72c.png">

**Comment by bp2008** [comment]
Nice

**Comment by bp2008** [comment]
Just updating this issue.  I'm still waiting for proper support from Blue Iris before starting work on a timeline user interface.  I am not aware of any developments yet.  Still waiting.

However @s-pw has created [a fork of UI3](https://github.com/s-pw/ui3) that has a stand-in version of the timeline feature which anyone can try in the meantime.  Because this had to utilize existing APIs, it works best on systems that do continuous recording.  I recommend extracting this fork to a subdirectory of the `www` folder so as to not interfere with normal updates.

I'm reopening this issue and will leave it open until timeline support is implemented officially.

**Comment by aesterling** [comment]
Can you speculate about how significant the necessary changes are in BI that would make this possible?

**Comment by bp2008** [comment]
Well there are really two parts to the needed changes.

1. A way to pull video from a group or a single camera, starting at a specific timestamp.  This will probably be the hard part since I'm guessing the existing timeline playback code was not architected to be reusable for web server streaming.
2. A way to query the server for metadata to render the timeline.  This should be fairly easy, as Blue Iris already uses all the same data for rendering its own timeline, so it should be a simple matter of formatting the needed information as JSON records.

**Comment by bp2008** [comment]
I started preparing a timeline control in UI3 on January 10th (4 days after my previous comment here).  When I told Ken I was working on it and asked for the lightning bolt icon he uses to indicate alerts in the local console's timeline, Ken told me he would be working on timeline stuff too.  So I guess that means this feature is coming sooner rather than later.

If anyone wants to try the timeline in UI3 in its current development state, you'll need a full copy of the UI3 source (I haven't merged certain library scripts into the libs-ui3.js file yet) and add a "timeline=1" URL parameter to the address bar.  It downloads and adapts data from the cliplist and alertlist commands, renders the data, and lets you zoom and pan.  But thats it.  There's no official API support yet so the data source is not final, and there's no clip playback wired in.  Change to a JPEG streaming profile to prevent the timeline from continuously auto-panning to the live point.

**Comment by bp2008** [comment]
The timeline is completed and available in [UI3-197](https://github.com/bp2008/ui3/releases/tag/197)!
