### ISSUE TITLE
No reencoding streaming

### ISSUE THREAD

**Issue by xjustbmw** [bp2008/ui3#65]
To save cpu. Is it possible to stream directly from the cameras?
Similar to direct to disk recording feature.
With no additional cpu reencoding required?

**Comment by bp2008** [comment]
No, Blue Iris does not offer this capability.

**Comment by geekifier** [comment]
@bp2008 is there an avenue to request features from BI? This would be a great feature to not only save CPU, but also increase quality. The quality in the web UI is so much lower than the recordings.

Also, it would be great to have h265 streaming since it's supported on some platforms. I'd be happy to submit those feature requests, and maybe others could chime in as well.

**Comment by bp2008** [comment]
Assuming the Blue Iris developer decides to go forward with passthrough streaming, set your expectations low.  There are a lot of technical challenges, and coordination between myself and the Blue Iris developer rarely goes quickly.  I would not expect the final experience to be as polished as what you get currently in UI3, and therefore this feature would probably be something you'd have to enable explicitly on each of your client devices by enabling passthrough on specific UI3 streaming profiles.
