### ISSUE TITLE
Toggle maximize video button is rather confused

### ISSUE THREAD

**Issue by arkid** [bp2008/ui3#67]
If you are in full screen mode with none of your browser interface visible then there is a button bottom right called "Toggle maximize video" which when pressed enables the top/left interface of UI3 whilst keeping the browser in full screen mode.

The problem is that once you've clicked it the button disappears and there isn't a button to go back to just full screen video feed.   This is confusing and means its much slower and more clicks to go back to the mode you were in previously.   Please keep this button constantly on the screen and change it's icon so that it can switch back to just the video feed.

The button I am referring to is below, second from right. 
![image](https://user-images.githubusercontent.com/3810108/110936514-c4891b80-830f-11eb-84f6-bfe12c92600d.png)

**Comment by bp2008** [comment]
You're right.  I can do better with this.  I've never been very happy with the icon I chose for that button either.

Do you have an opinion about these?

![image](https://user-images.githubusercontent.com/5639911/110956332-c0590000-8307-11eb-9f00-b0c8b1c8947a.png)

![image](https://user-images.githubusercontent.com/5639911/110956440-dbc40b00-8307-11eb-8f24-cf7eed06b048.png)

![image](https://user-images.githubusercontent.com/5639911/110956360-c7800e00-8307-11eb-9bcc-6677568dfc1f.png)

I couldn't find a reverse version of that last one but I could probably modify the existing one to create it.

I get nearly all of UI3's icons from [material.io](https://material.io/resources/icons/?style=baseline) since the original graphic designer ruppmeister disappeared.  If you have any better suggestions, I'm all ears.

**Comment by arkid** [comment]
Just for general reference, I use http://thenounproject.com/.    Their collection is just massive.     I'm personally ok with the current icon but modified in some form for the reverse scenario.

**Comment by bp2008** [comment]
Implemented in [UI3-144](https://github.com/bp2008/ui3/releases/tag/144).

**Comment by arkid** [comment]
Amazing thanks!
