### ISSUE TITLE
disable sound alarm on triggers and enable sound alarm on confirmed alerts

### ISSUE THREAD

**Issue by githubDiversity** [bp2008/ui3#73]
Is that already possible or easy to implement?

currently I have deepstack as AI and only want to hear an alarm on AI confirmed alerts.

Now it's like still having false alarms, by means of audio, even though AI is implemented.

**Comment by bp2008** [comment]
You'd have to ask Blue Iris support for this.  UI3 just plays the configured sound when Blue Iris tells it to.

**Comment by githubDiversity** [comment]
I see, well then in that case I implemented a small bit of ES6 to make UI3 a bit more independent and determine for itself when to sound the alarm on confirmed alarm. It forks like a charm for me and my specific needs.

I would understand if you are hesitant to implement something useful like this if it might render the IOS and Android paid app obsolete, in that case I'll not share the code.

But if you would implement functionality like this then I will give it to you so you can either use it directly or use it as inspiration.
BTW in that case I'll make a service worker for web push alarms as well. (Android only)

Ahh with something like cordova or phonegap there is no end to the possibilities then.

**Comment by bp2008** [comment]
Lol.  I have no interest in limiting UI3 to make the mobile apps look better.  What would give you that idea?

I'm always willing to look at community contributions. If nothing else, it helps me grow as a developer to see how others' solution for a problem differs from my own.  As you've surely noticed, it isn't technically difficult to implement this, but it requires polling the alert list rather than simply parsing the metadata included in Blue Iris's video stream.  The fact you would go to the effort of implementing this yourself tells me you really care about this capability.

**Comment by bp2008** [comment]
I'm also very curious how you think you can utilize web push without being able to extend Blue Iris's web server.

**Comment by githubDiversity** [comment]
I think we have a bit of a misunderstanding. I never meant to suggest anything related to limiting UI3. On the contrary, I meant let's make it the best it can be. But I would understand if you are hesitant because it kinda invalidates the whole native mobile app efforts.

For server send events yes we'd need to alter the BI web server. But I am refering to the Push (notifications) API and if I am not mistaken for web push we only need a service worker (Android only) or if we are hellbend on supporting IOS which I would advice against for political reasons sure we could make a cordova wrapper

**Comment by githubDiversity** [comment]
I am readying up regarding push notifications  as we speak and beginning to suspect I could have misunderstood the concept. What I was aiming for was a way to background poll the alert list and push a notification on new alert

**Comment by githubDiversity** [comment]
Ahh I just realized that for SSL support one needs to resort to using stunnel (a proxy of sorts)

So there is really nothing we can't do with a simple executable in the UI3 folder putting it between stunnel and BI.

So I am al confident again that not even the sky is the limit

**Comment by githubDiversity** [comment]
not even between stunnel and BI. just setup an IIS (or your web server of choice) proxy before BI and we can do away with stunnel as well. making things a lot easier

**Comment by githubDiversity** [comment]
or host the whole UI3 inside IIS or kestrel or what ever web server one would like. why not ;)

**Comment by bp2008** [comment]
> I think we have a bit of a misunderstanding. I never meant to suggest anything related to limiting UI3. On the contrary, I meant let's make it the best it can be. But I would understand if you are hesitant because it kinda invalidates the whole native mobile app efforts.

I don't like the mobile apps.  Doesn't bother me making them less relevant!!

> For server send events yes we'd need to alter the BI web server.

Yeah, I've had relatively little success in getting Ken to make changes in the BI web server.  There have been some successes like supporting parameter-driven H.264 streaming and the clip export API, but a lot of things I've asked for over the years just don't happen.

> But I am refering to the Push (notifications) API and if I am not mistaken for web push we only need a service worker (not supported on IOS) or if we are hellbend on supporting IOS which I would advice against for political reasons sure we could make a cordova wrapper

Something still needs to send out the notification.  I don't think you'd be able to get a service worker to continually poll for changes to the alert list while you don't have UI3 open.

For web push you do need HTTPS and quite a bit of server-side logic for handling the client registrations and sending out messages.

> I am readying up regarding push notifications as we speak and beginning to suspect I could have misunderstood the concept. What I was aiming for was a way to background poll the alert list and push a notification on new alert

The "push" part of push notifications refers to the server sending a message to a cloud service (typically run by the web browser vendor) which gets forwarded to a web browser.  It can't be done without server-side logic.  You can do notifications without a server, but you can't do "push" notifications, and I don't think you can get a service worker to poll the alert list in the background while UI3 is not open.

>  just setup an IIS (or your web server of choice) proxy before BI

I've been mildly interested in [doing that](https://github.com/bp2008/BlueIrisWebserverExtensions) for a long time.  That isn't even my first attempt at such a project.

Running your own custom proxy server could provide a path to implementing new features that Blue Iris doesn't natively support, such as HTTPS, automatic LetsEncrypt certificates, web push, websockets, and more.  But every time I get started on such a project, I am discouraged by the numerous challenges involved and I don't get very far.

**Comment by bp2008** [comment]
One thing about spending a lot of development effort on a proxy server that adds features to UI3 is that relatively few people will ever know about it and even fewer will ever use it.  It also creates a maintenance burden for every user, as it would need to be installed and configured and updated separately from Blue Iris.  And it makes UI3 development more difficult if some features only work through a specific proxy server which may or may not be out of sync in terms of compatibility.

**Comment by githubDiversity** [comment]
> but a lot of things I've asked for over the years just don't happen.

Understood. Well then that makes me even more confident that a good reverse proxy implementation is the way forward.

Regarding the maintenance aspect for users; Perhaps we can simply not publish your BIWS extentions in a compiled state, let IIS handle that at request time if it detects changes (that are brought about by an BI update).

How to setup IIS with a self signed certificate for HTTPS is easy enough and we could notify users of how to do that in the UI3 itself where you have total control of what, when and how to show users information..

In the end I for one really need this functionality as to be always alerted when a confirmed alert happens. Otherwise for me it is the same as having no camera's at all. I really believe this is true for about 70% of BI users as well, especially the recidential users

I am going ahead with your BIWS extensions and see how far I get with those. I am not sure though if  focussing on IIS will disable win 10 home users from implementing this functionality

**Comment by githubDiversity** [comment]
Could it be that the repository is missing the BPUtil project?

When opening in VS2019 I get this error while opening the solution. And indeed it appears to be missing and there is a reference to that project.

\BlueIrisWebserverExtensions-master\BPUtil\BPUtil\BPUtil.csproj : error  : The project file could not be loaded. Could not find a part of the path 'BlueIrisWebserverExtensions-master\BPUtil\BPUtil\BPUtil.csproj'.  \BlueIrisWebserverExtensions-master\BPUtil\BPUtil\BPUtil.csproj

**Comment by githubDiversity** [comment]
I think there is no longer a way around a reverse proxy based on the lighthouse report from chrome devtools.
HTTP2 for example and proper caching headers and the likes.

The use of jquery seems to have a vulnerability. I would recommend removing jquery all together as it has become obselete.

[UI3master-chrome-devtools-lighthouse-report.html.txt](https://github.com/bp2008/ui3/files/6433816/UI3master-chrome-devtools-lighthouse-report.html.txt)

I will go ahead and implement the IIS reverse proxy now with server push. it's time for me to learn about how it works anyways so this is really the best real life application to do it on. I won't be using your BIWS extentions though until I can build it.

**Comment by githubDiversity** [comment]
>  I am not sure though if focussing on IIS will disable win 10 home users from implementing this functionality

I forgot about the hostable IIS web core. IIUC this will mean that we can fully automate the whole process of setting up IIS reverse proxy including ssl even for win 10 home users

**Comment by bp2008** [comment]
I don't use IIS for projects that don't need to be highly scalable.  The additional complexity causes too many headaches.  I've been using IIS in my professional work for a decade and it still finds new ways to surprise or disappoint me.

>Could it be that the repository is missing the BPUtil project?

Yes.  [BPUtil](https://github.com/bp2008/BPUtil) is my personal utility project that I reference in most things I write.  It includes my own web server code, which is what I used in the [BlueIrisWebserverExtensions](https://github.com/bp2008/BlueIrisWebserverExtensions) project.  .NET actually has a built-in HTTP server capability separate from IIS, but I prefer my own implementation because I can make it do anything I want without having my hands tied by someone else's feature set.

The only thing BlueIrisWebserverExtensions currently does is HTTPS proxying and I don't remember if I got it working perfectly or not.  I haven't looked at it in over a year.

> The use of jquery seems to have a vulnerability. I would recommend removing jquery all together as it has become obselete.

jQuery is deeply entrenched into UI3.  Removing it is impractical.  Just updating it to version 3.x would be a big chore with no practical benefit.

> I forgot about the hostable IIS web core. IIUC this will mean that we can fully automate the whole process of setting up IIS reverse proxy including ssl even for win 10 home users

You can automate full-blown IIS configuration too.  Microsoft has APIs for most of the things that can't simply be done by editing your project's `web.config` file.

**Comment by githubDiversity** [comment]
I tend to agree with any jquery vulnerabilities not being an issue as long as UI3 stays a private matter. Which in my case it will be.
I do suggest to tree shake all the unused jquery code before packing it and perhaps any vulnerabilities will be shaken out as well. 

Anyway I have now a working demo on asp.net core 5 of web push working on android chrome with custom airaid.mp3 sound and all. Self signed certificates won't work on android firefox and mobile chrome so I had to use an actual SSL certificate but since it is wildcard it's not a problem.

This is soo freakishly awesome in where my phone can be sleeping with nothing loaded and boom there goes the air raid only 3 seconds after pushing the notification. I am happy.

If you'd like to avoid IIS you could consider kestrel or even nodejs. case in point there is no more reason for UI3 not to be full blown. If you'd like my help I am happy to. Just let me know.

**Comment by bp2008** [comment]
> I do suggest to tree shake all the unused jquery code before packing it and perhaps any vulnerabilities will be shaken out as well.

Can you even do that (effectively) with jquery?  Its core design predates ... just about everything.

> Anyway I have now a working demo on asp.net core 5 of web push working on android chrome with custom airaid.mp3 sound and all. Self signed certificates won't work on android firefox and mobile chrome so I had to use an actual SSL certificate but since it is wildcard it's not a problem.

Awesome.  Well done.  That was quick.

> If you'd like to avoid IIS you could consider kestrel or even nodejs. case in point there is no more reason for UI3 not to be full blown. If you'd like my help I am happy to. Just let me know.

nodejs is not my idea of a user-friendly web server either.  kestrel, I have no idea.  I've never run it.  That is what .NET core web apps use when you run them on linux, right?

Alas, there's a big difference in the effort required to build a prototype of something for yourself and to build a version that is user-friendly and bulletproof enough to be installed and operated by clueless end users, that also won't blow up when Blue Iris does something unexpected.  And then to support it when it blows up anyway.

I brought up implementing web push with Ken (Blue Iris) in 2019.  I didn't hear back, which is normal when I talk about things that mean work for him.

**Comment by bp2008** [comment]
Since we're on the topic, some things I've thought about implementing in a BI web server proxy:

- HTTPS
- automatic signed certificates via LetsEncrypt (only works if HTTP port 80 is open of course)
- web push (obviously)
- WebSocket server
  - The proxy server could poll for data updates and push them to UI3 via the web socket, saving network bandwidth.  Maybe not worth the effort though.
  - two-way audio
  - two-way video (perhaps you have noticed that "broadcast from client app" option when you configure a camera in Blue Iris)
  - originally I wanted to use WebSockets for video streaming, but that was back when only Chrome supported `ReadableStream` via `fetch`.  WebSockets aren't really needed for server-to-client video streaming anymore.
- Provide direct links to camera web interfaces (probably not proxied for security reasons, just linked so you could access them conveniently if you were on the local subnet)
- 2FA or other alternate authentication
- API to remotely control UI3 instances running on other devices

In the end, I'm lazy and I have too many other priorities.

**Comment by githubDiversity** [comment]
Is there anyway I can send you private messages? It feel I have inadvertently  abused an github issue thread to start a conversation of an exploratory nature. 

Anyway, as far as I understand it kestrel is the default web server for asp.net core. I use it in one of my projects including SSL. Not sure about scalability though.

I understand all too well regarding having priorities, it does not make one lazy. We need time to enjoy life, friends and family as well.

 Regarding your feature list, I think for me personally I really could do with 2 way audio for a doorbell system and I think I'll try implementing something to that effect sooner or later.

I'll begin to see if I can shake some jquery out of the code. the less of it the better.

BTW, which browsers are your supporting? I would recommend only supporting the latest versions of ios safari, mobile chrome, mobile firefox and their desktop counter parts. That would render most if not all polyfill libraries obsolete.

As for the decoding, I have half a mind to try moving that to web assembly as that is something I wanted to tinker with for a long time but have not found a good reason to yet.

**Comment by bp2008** [comment]
> Is there anyway I can send you private messages?

https://ipcamtalk.com/conversations/add?to=bp2008

> BTW, which browsers are your supporting?

As many as possible.  There are a lot of browsers in embedded devices like smart TVs that rarely/never get updates but people still try to use them for UI3.  I want it to still work on those whenever possible.  So I try to keep things working in IE (9+) because that is a good baseline.  Not all features work depending on browser capabilities of course.  The top of ui3.js has a lot of feature detection code to disable unsupported features.

> As for the decoding, I have half a mind to try moving that to web assembly as that is something I wanted to tinker with for a long time but have not found a good reason to yet.

Right, so UI3's original H.264 decoder (the "JavaScript" option if you look in the H.264 player dropdown) was built with emscripten but I was unable to get it working when I targeted webassembly for the build.  I haven't messed with it in years. I'm sure things have improved and maybe you'd have more success.  https://github.com/kazuki/video-codec.js was the source for that.  I think most of the potential webassembly performance gain comes from supporting threads, but I'm not sure if H.264 decoding is even done with multiple threads normally.

**Comment by githubDiversity** [comment]
my advice is to ignore/abandon the push API. It is just too brittle. (And thinking of it again yes it makes sense to never rely on service beyond ones control (to some extend of course).)

It starts out all cool and behaving properly but soon enough the random shit comes. not fireing when needed, firing when not needed and all in between.

So I have now fallen back to on confirmed alert -> email to -> android k9 with dedicated account -> still working like a champ

I will let you all know if this also breaks down
