### ISSUE TITLE
use Video 2.0 in external application

### ISSUE THREAD

**Issue by markusuidl** [bp2008/ui3#82]
this is not a bug, moreover its a request for documentation to the video 2.0 stream

i see UI3 uses the following url to play MPEG

`http://<ip>:<port/video/<cam>/2.0?session=xxxxxxxxxxxxxx&audio=0&stream=0&q=20&h=1080&kbps=1000&gop=1000&zfl=1&preset=1&extend=2 `

if i paste the url to a player like VLC nothing happens, VLC keeps loading and displays nothing.

propably it does not work because of missing session token? how can i get it working?
blue iris manual has no information here and with the other urls like
`h264/<cam>/temp.ts
h264/<cam>/temp.h264`
i can not get the good quality as in UI3, the params like q/h/gop are not working too.

**Comment by bp2008** [comment]
The streaming format used by that request is entirely proprietary -- I had to get the BI developer to explain the protocol to me.  UI3's source code is the most complete documentation of that protocol that there is, but you'll need to understand JavaScript to make much sense of it:  https://github.com/bp2008/ui3/blob/9623274f985fa0e8e570d65d27624cf8a7112ec8/ui3/ui3.js#L22050

Blue Iris offers RTSP server capability since a few months ago, and most of the same encoding arguments are available there too. 
 That will be the easiest way to get a good live stream out of Blue Iris and into third-party players.  https://ipcamtalk.com/threads/5-3-1-july-16-2020-your-blue-iris-web-server-now-is-also-an-rtsp-server.49571/
