### ISSUE TITLE
FPS in status bar updating too frequently

### ISSUE THREAD

**Issue by milosivanovic** [bp2008/ui3#96]
It should be debounced to update a couple times a second (like it was before) instead of after every frame, which it seems to be doing now.

**Comment by bp2008** [comment]
Ah, well I suppose that is a matter of opinion.  It used to be that I was using the 'time changed' event from the HTML5 video player to update the GUI status (FPS meter and seek position when playing a clip).  That event only fires a few times per second.

Then some months ago I added a polling method to build my own 'frame rendered' event specifically so that the update rate of the GUI would be better synchronized with the video like it is when using any of UI3's other video player components.

Is there really a meaningful gain from limiting the update rate of the GUI, next to the cost of rendering the video I mean?

**Comment by milosivanovic** [comment]
@bp2008 I see. At least you know exactly what caused it.

DOM updates to incur a cost, especially this frequently, and it's jarring to the eye. My LCD screen cannot even keep up with the rendering rate to properly display the number. For example, for a 30FPS camera, it might go between 29 and 30 15 times per second showing a blurry mess. I think it would be cleaner to debounce these updates. Additionally, humans cannot read/process changing visual information that quickly anyway.

**Comment by bp2008** [comment]
Heh.  Well I will debounce the FPS meter update rate.  Not like it is hard for me.

**Comment by bp2008** [comment]
This and some other related optimizations are done in [commit 6bc93c7](https://github.com/bp2008/ui3/commit/6bc93c75a984a8cc10b66f5eb3bed0ee04b63717) and will be released in UI3-184.  Thanks for the feedback!
